### ISSUE TITLE
ByteBuffer.flip() NoSuchMethodError

### ISSUE THREAD

**Issue by Zappykeyboard** [biagioT/java-pec-parser#2]
Ciao, Stavo testando la libreria, ma mi sono imbattuto su questo errore:
`java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at app.tozzi.mail.pec.util.IOUtils.fastCopy(IOUtils.java:121)
	at app.tozzi.mail.pec.util.IOUtils.fastCopy(IOUtils.java:112)
	at app.tozzi.mail.pec.util.IOUtils.getContent(IOUtils.java:104)
	at app.tozzi.mail.pec.util.IOUtils.createDataSource(IOUtils.java:38)...`

Leggendo in giro, sembra che il problema sia causato da una incompatibilità tra versioni di java: https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip

Il mio progetto utilizza java 8. C'è possibilità di aggirare il problema?

**Comment by giuseppepellegrinodev** [comment]
Confermo il problema.

**Comment by biagioT** [comment]
fixed in 3.0.2
